import { forwardRef, Module } from '@nestjs/common';

import { ComunModule } from '../../comun';

import { DominioModule } from '../dominio';
import { InfraestructuraModule } from '../infraestructura';
import {
  SERVICIO_FACTORY_PROVIDER,
  TRAMITE_SERVICIO_PROVIDER,
  INFORME_SERVICIO_PROVIDER,
  SUJETO_IDENTIFICADO_SERVICIO_PROVIDER,
  NOTIFICACION_SERVICIO_PROVIDER,
  REUNION_SERVICIO_PROVIDER,
  RESOLUCION_SERVICIO_PROVIDER,
  ACTOS_ADMINISTRATIVOS_SERVICIO_PROVIDER,
  PAGO_CPT_SERVICIO_PROVIDER,
  VIAJE_SERVICIO_PROVIDER,
  PROVIDENCIA_SERVICIO_PROVIDER,
  DOCUMENTO_SERVICIO_PROVIDER

} from './servicios';

@Module({
  imports: [
    ComunModule,
    DominioModule,
    forwardRef(() => InfraestructuraModule),
  ],
  exports: [SERVICIO_FACTORY_PROVIDER],
  providers: [
    SERVICIO_FACTORY_PROVIDER,
    TRAMITE_SERVICIO_PROVIDER,
    INFORME_SERVICIO_PROVIDER,
    SUJETO_IDENTIFICADO_SERVICIO_PROVIDER,
    NOTIFICACION_SERVICIO_PROVIDER,
    REUNION_SERVICIO_PROVIDER,
    RESOLUCION_SERVICIO_PROVIDER,
    ACTOS_ADMINISTRATIVOS_SERVICIO_PROVIDER,
    PAGO_CPT_SERVICIO_PROVIDER,
    VIAJE_SERVICIO_PROVIDER,
    PROVIDENCIA_SERVICIO_PROVIDER,
    DOCUMENTO_SERVICIO_PROVIDER
  ],
})
export class AplicacionModule {}
