import {MigrationInterface, QueryRunner} from "typeorm";

export class ConsultaPrevia1691370466545 implements MigrationInterface {
    name = 'ConsultaPrevia1691370466545'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "consulta-previa"."resolucion" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "idresolucion" SERIAL NOT NULL, "fk_idtramite" integer, "informe" character varying, "resolucion" character varying, "informeaprobado" boolean NOT NULL DEFAULT false, "actosadministrativos" boolean NOT NULL DEFAULT false, "resolucionpdf" character varying, "flujo" character varying, "referencia" character varying, CONSTRAINT "PK_b9be3e76a2ea81e56f45edf7aa1" PRIMARY KEY ("idresolucion"))`);
        await queryRunner.query(`CREATE TABLE "consulta-previa"."providencia" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "idprovidencia" SERIAL NOT NULL, "fk_idtramite" integer, "correlativo" character varying, "referencia" character varying, "providenciapdf" character varying, "flujo" character varying, CONSTRAINT "PK_7945ed687634da8cc5cfb4b662a" PRIMARY KEY ("idprovidencia"))`);
        await queryRunner.query(`CREATE TABLE "consulta-previa"."sujetoidentificado" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "idsujeto" SERIAL NOT NULL, "fk_idinforme" integer, "comunidad" character varying, "autoridad" character varying, "telefono" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_30e746b1f1385e434c9cd54464e" PRIMARY KEY ("idsujeto"))`);
        await queryRunner.query(`CREATE TABLE "consulta-previa"."informe" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "idinforme" SERIAL NOT NULL, "fk_idtramite" integer, "correlativo" character varying, "referencia" character varying, "informepdf" character varying, "asunto" character varying, "flujo" character varying, CONSTRAINT "PK_96d28d9730d485d45d75211a655" PRIMARY KEY ("idinforme"))`);
        await queryRunner.query(`CREATE TABLE "consulta-previa"."reunion" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "idreunion" SERIAL NOT NULL, "fk_idnotificacion" integer, "nroreunion" character varying, "conacuerdo" boolean NOT NULL DEFAULT false, "sinacuerdo" boolean NOT NULL DEFAULT false, "motivo" character varying, "reunionrealizada" boolean NOT NULL DEFAULT false, "actareunionpdf" character varying, "estado" character varying, "flujo" character varying, CONSTRAINT "REL_4973568d96d56889cd2f12ce11" UNIQUE ("fk_idnotificacion"), CONSTRAINT "PK_cdcd68f004cc37d501b1323b257" PRIMARY KEY ("idreunion"))`);
        await queryRunner.query(`CREATE TABLE "consulta-previa"."notificacion" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "idnotificacion" SERIAL NOT NULL, "fk_idtramite" integer, "notificado" character varying, "direcciondpto" character varying, "notificacionpdf" character varying, "flujo" character varying, "representanteminero" boolean, "representantecomunidad" boolean, "sifde" boolean, "comunidad" character varying, "nroreunion" character varying, CONSTRAINT "PK_855ba5f71313d50f3b8c9909d09" PRIMARY KEY ("idnotificacion"))`);
        await queryRunner.query(`CREATE TABLE "consulta-previa"."tramite" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "idtramite" SERIAL NOT NULL, "correlativo" character varying, "codigounico" integer NOT NULL DEFAULT '0', "areaminera" character varying, "clasificacion" character varying, "nrocuadricula" integer NOT NULL DEFAULT '0', "departamento" character varying, "provincia" character varying, "municipio" character varying, "estado" character varying, CONSTRAINT "PK_7059550436eccb000ea09aca81d" PRIMARY KEY ("idtramite"))`);
        await queryRunner.query(`CREATE TABLE "consulta-previa"."pagocpt" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "idpago" SERIAL NOT NULL, "fk_idactos" integer NOT NULL, "pagorealizado" boolean NOT NULL DEFAULT false, "flujo" character varying, "diasviaje" integer, "tipoviaje" character varying, "montototal" integer NOT NULL DEFAULT '0', "apm" character varying, "descripcion" character varying, "estado" character varying, "transaccion" integer NOT NULL DEFAULT '0', "fechaactual" TIMESTAMP NOT NULL DEFAULT NOW(), "canal" character varying, "cpt" integer NOT NULL DEFAULT '0', "fechavigencia" TIMESTAMP, "fechavalidez" TIMESTAMP, "iniciovigencia" TIMESTAMP, "tiposervicio" character varying, CONSTRAINT "REL_0a0dd54599b4c81234414040de" UNIQUE ("fk_idactos"), CONSTRAINT "PK_f44fa9355e4b8751b8944ad7c4a" PRIMARY KEY ("idpago"))`);
        await queryRunner.query(`CREATE TABLE "consulta-previa"."viaje" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "idviaje" SERIAL NOT NULL, "fk_idactos" integer, "fechainicio" TIMESTAMP, "fechafin" TIMESTAMP, "descripcion" character varying, "nroformulario" character varying, "formulariopdf" character varying, CONSTRAINT "REL_2e9fa712def461e014af810173" UNIQUE ("fk_idactos"), CONSTRAINT "PK_7bc412cd3477946407d4bb339ed" PRIMARY KEY ("idviaje"))`);
        await queryRunner.query(`CREATE TABLE "consulta-previa"."actosadministrativos" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "idactos" SERIAL NOT NULL, "fk_idtramite" integer, "fk_idresolucion" integer, "viajerealizado" boolean NOT NULL DEFAULT false, "flujo" character varying, "estado" character varying, CONSTRAINT "PK_c1f4ff2f46f318f9f3f760ba14a" PRIMARY KEY ("idactos"))`);
        await queryRunner.query(`CREATE TABLE "control-accesos"."GRUPO" ("GRUPO_ID" SERIAL NOT NULL, "CODIGO" character varying NOT NULL, "NOMBRE" character varying NOT NULL, "DESCRIPCION" character varying NOT NULL, CONSTRAINT "PK_e20245ab62e4585f38f8f3874b2" PRIMARY KEY ("GRUPO_ID"))`);
        await queryRunner.query(`CREATE TABLE "control-accesos"."ROL_CUENTA" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP, "ROL_CUENTA_ID" SERIAL NOT NULL, "INST_REGISTRO" TIMESTAMP NOT NULL, "FEC_INICIO" TIMESTAMP NOT NULL, "FEC_CONCLUSION" TIMESTAMP NOT NULL, "ROL_ID" integer NOT NULL, "CUENTA_ID" integer NOT NULL, CONSTRAINT "PK_c3483a513251024a8202e9d6c19" PRIMARY KEY ("ROL_CUENTA_ID"))`);
        await queryRunner.query(`CREATE TABLE "control-accesos"."ROL" ("ROL_ID" SERIAL NOT NULL, "CODIGO" character varying NOT NULL, "NOMBRE" character varying NOT NULL, "GRUPO_ID" integer NOT NULL, CONSTRAINT "PK_81a05dd65e268cc49639dbd0d70" PRIMARY KEY ("ROL_ID"))`);
        await queryRunner.query(`CREATE TABLE "control-accesos"."USUARIO" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP, "CUENTA_ID" integer NOT NULL, "NOMBRE" character varying NOT NULL, "APELLIDO" character varying NOT NULL, "NOM_PUBLICO" character varying NOT NULL, "CORREO_ELECTRONICO" character varying NOT NULL, CONSTRAINT "REL_f4e92e02536b70e736a0e6f0a0" UNIQUE ("CUENTA_ID"), CONSTRAINT "PK_f4e92e02536b70e736a0e6f0a00" PRIMARY KEY ("CUENTA_ID"))`);
        await queryRunner.query(`CREATE TABLE "control-accesos"."CUENTA" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP, "CUENTA_ID" SERIAL NOT NULL, "CODIGO" character varying NOT NULL, "MODO_AUTENTICACION" character varying NOT NULL, "NOMBRE" character varying NOT NULL, "CLAVE" character varying NOT NULL, "CONTRASENIA" character varying NOT NULL, "ESTA_AUTORIZADA" boolean NOT NULL, "INST_ULT_SESION" TIMESTAMP, "NUM_INT_FALLIDOS" integer NOT NULL, "ESTA_BLOQUEADA" boolean NOT NULL, "INST_ULT_BLOQUEO" TIMESTAMP, CONSTRAINT "REL_98117e3745f7518f76b23ea661" UNIQUE ("CUENTA_ID"), CONSTRAINT "PK_98117e3745f7518f76b23ea6613" PRIMARY KEY ("CUENTA_ID"))`);
        await queryRunner.query(`CREATE TABLE "personal"."INFO_LABORAL" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "PERS_ID" integer NOT NULL, "TIPO_LABORAL" character varying NOT NULL, "CORREO_INSTITUCIONAL" character varying, "NUM_INTERNO" character varying, "ESTADO" character varying NOT NULL, "CUENTA" character varying, "UNI_ORG_ID" integer NOT NULL, "PUESTO_ID" integer, CONSTRAINT "REL_4eff75d32d86de14ab346208f6" UNIQUE ("PERS_ID"), CONSTRAINT "PK_4eff75d32d86de14ab346208f67" PRIMARY KEY ("PERS_ID"))`);
        await queryRunner.query(`CREATE TABLE "personal"."PARAMETRO" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "PARAM_ID" SERIAL NOT NULL, "TIPO" character varying NOT NULL, "ORDEN" integer NOT NULL, "VALOR" character varying NOT NULL, "TEXTO" character varying NOT NULL, "ESTA_ACTIVO" boolean NOT NULL, CONSTRAINT "PK_94c63024a7becf4a64d41aa393e" PRIMARY KEY ("PARAM_ID"))`);
        await queryRunner.query(`CREATE TABLE "personal"."PERSONA" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "PERS_ID" SERIAL NOT NULL, "CODIGO" character varying NOT NULL, "PRIM_APELLIDO" character varying NOT NULL, "SEG_APELLIDO" character varying, "NOMBRE" character varying NOT NULL, "NUM_DOCUMENTO" character varying NOT NULL, "EXPEDICION" character varying NOT NULL, "FEC_NACIMIENTO" date NOT NULL, "CORREO_PERSONAL" character varying NOT NULL, "CELULAR_PERSONAL" character varying NOT NULL, CONSTRAINT "PK_bb957e6dd678bf1fe53d0b9928f" PRIMARY KEY ("PERS_ID"))`);
        await queryRunner.query(`CREATE TABLE "personal"."PUESTO_PERSONA" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "PUESTO_PERS_ID" SERIAL NOT NULL, "TIPO_MOVILIDAD" character varying NOT NULL, "TIPO_LABORAL" character varying NOT NULL, "FEC_INICIO" date NOT NULL, "FEC_CONCLUSION" date, "ES_INTERINATO" boolean NOT NULL, "TIENE_DESVINCULACION" boolean NOT NULL, "ESTADO" character varying NOT NULL, "PUESTO_ID" integer, "PERS_ID" integer NOT NULL, "UNI_ORG_ID" integer NOT NULL, CONSTRAINT "PK_487afb562ceb1ea9dd25c445c32" PRIMARY KEY ("PUESTO_PERS_ID"))`);
        await queryRunner.query(`CREATE TABLE "personal"."PUESTO" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "PUESTO_ID" SERIAL NOT NULL, "NOMBRE" character varying NOT NULL, "DESCRIPCION" character varying, "NIVEL_JERARQUICO" integer NOT NULL, "ESTA_ACTIVO" boolean NOT NULL, "UNI_ORG_ID" integer NOT NULL, CONSTRAINT "PK_02c0577395f773ffd260eddf8fb" PRIMARY KEY ("PUESTO_ID"))`);
        await queryRunner.query(`CREATE TABLE "personal"."UNI_ORGANIZACIONAL" ("_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, "_USU_MODIFICACION" character varying, "_INST_MODIFICACION" TIMESTAMP WITH TIME ZONE, "_USU_ELIMINACION" character varying, "_INST_ELIMINACION" TIMESTAMP WITH TIME ZONE, "UNI_ORG_ID" SERIAL NOT NULL, "CODIGO" character varying NOT NULL, "SIGLA" character varying NOT NULL, "NOMBRE" character varying NOT NULL, "ESTA_ACTIVA" boolean NOT NULL, "UNI_ORG_SUPERIOR_ID" integer, CONSTRAINT "PK_2ec4c53379f69a461437305638e" PRIMARY KEY ("UNI_ORG_ID"))`);
        await queryRunner.query(`CREATE TABLE "personal"."FOTOGRAFIA" ("PERS_ID" integer NOT NULL, "ARCHIVO" character varying NOT NULL, "TIPO_MIME" character varying NOT NULL, "EXTENSION" character varying NOT NULL, "TAMANIO" integer NOT NULL, "_USU_CREADOR" character varying NOT NULL, "_INST_CREACION" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "REL_6d432f4b03a985d8c1d62f1312" UNIQUE ("PERS_ID"), CONSTRAINT "PK_6d432f4b03a985d8c1d62f13124" PRIMARY KEY ("PERS_ID"))`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."resolucion" ADD CONSTRAINT "FK_61b40bd21c02dfe058232b54a34" FOREIGN KEY ("fk_idtramite") REFERENCES "consulta-previa"."tramite"("idtramite") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."providencia" ADD CONSTRAINT "FK_6dbbe7b7d52eb106fd39fdaf459" FOREIGN KEY ("fk_idtramite") REFERENCES "consulta-previa"."tramite"("idtramite") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."sujetoidentificado" ADD CONSTRAINT "FK_3a5ad1260d3102d8a8b7d53ceac" FOREIGN KEY ("fk_idinforme") REFERENCES "consulta-previa"."informe"("idinforme") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."informe" ADD CONSTRAINT "FK_d5052c8c299e6cb52949aed2b43" FOREIGN KEY ("fk_idtramite") REFERENCES "consulta-previa"."tramite"("idtramite") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."reunion" ADD CONSTRAINT "FK_4973568d96d56889cd2f12ce114" FOREIGN KEY ("fk_idnotificacion") REFERENCES "consulta-previa"."notificacion"("idnotificacion") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."notificacion" ADD CONSTRAINT "FK_6d4c5eb7bc4c451fbe8842a3fa8" FOREIGN KEY ("fk_idtramite") REFERENCES "consulta-previa"."tramite"("idtramite") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."pagocpt" ADD CONSTRAINT "FK_0a0dd54599b4c81234414040dec" FOREIGN KEY ("fk_idactos") REFERENCES "consulta-previa"."actosadministrativos"("idactos") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."viaje" ADD CONSTRAINT "FK_2e9fa712def461e014af810173d" FOREIGN KEY ("fk_idactos") REFERENCES "consulta-previa"."actosadministrativos"("idactos") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."actosadministrativos" ADD CONSTRAINT "FK_d0dd43ffeae86e51119bd06b0c1" FOREIGN KEY ("fk_idtramite") REFERENCES "consulta-previa"."tramite"("idtramite") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."actosadministrativos" ADD CONSTRAINT "FK_108deb1b6b2f15f68dfe22720a2" FOREIGN KEY ("fk_idresolucion") REFERENCES "consulta-previa"."resolucion"("idresolucion") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "control-accesos"."ROL_CUENTA" ADD CONSTRAINT "FK_eaef5523322868c13f8391f594c" FOREIGN KEY ("ROL_ID") REFERENCES "control-accesos"."ROL"("ROL_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "control-accesos"."ROL_CUENTA" ADD CONSTRAINT "FK_3a29ae5572589b33336f4daba87" FOREIGN KEY ("CUENTA_ID") REFERENCES "control-accesos"."CUENTA"("CUENTA_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "control-accesos"."ROL" ADD CONSTRAINT "FK_a5f1d80b333b17b67938cb50437" FOREIGN KEY ("GRUPO_ID") REFERENCES "control-accesos"."GRUPO"("GRUPO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "control-accesos"."USUARIO" ADD CONSTRAINT "FK_f4e92e02536b70e736a0e6f0a00" FOREIGN KEY ("CUENTA_ID") REFERENCES "control-accesos"."CUENTA"("CUENTA_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "control-accesos"."CUENTA" ADD CONSTRAINT "FK_98117e3745f7518f76b23ea6613" FOREIGN KEY ("CUENTA_ID") REFERENCES "control-accesos"."USUARIO"("CUENTA_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal"."INFO_LABORAL" ADD CONSTRAINT "FK_4eff75d32d86de14ab346208f67" FOREIGN KEY ("PERS_ID") REFERENCES "personal"."PERSONA"("PERS_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal"."INFO_LABORAL" ADD CONSTRAINT "FK_e4de6b93ddfcdc477096ba84d15" FOREIGN KEY ("UNI_ORG_ID") REFERENCES "personal"."UNI_ORGANIZACIONAL"("UNI_ORG_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal"."INFO_LABORAL" ADD CONSTRAINT "FK_a72764efdda4ee04814aee215b6" FOREIGN KEY ("PUESTO_ID") REFERENCES "personal"."PUESTO"("PUESTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal"."PUESTO_PERSONA" ADD CONSTRAINT "FK_44111009eb8b30558c4e7b61610" FOREIGN KEY ("PUESTO_ID") REFERENCES "personal"."PUESTO"("PUESTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal"."PUESTO_PERSONA" ADD CONSTRAINT "FK_b918489c812772e156f97383be0" FOREIGN KEY ("PERS_ID") REFERENCES "personal"."PERSONA"("PERS_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal"."PUESTO_PERSONA" ADD CONSTRAINT "FK_bf6a131bac57fc997adc0dd514a" FOREIGN KEY ("UNI_ORG_ID") REFERENCES "personal"."UNI_ORGANIZACIONAL"("UNI_ORG_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal"."PUESTO" ADD CONSTRAINT "FK_1cf2e9a0155543e21f6752e3b8b" FOREIGN KEY ("UNI_ORG_ID") REFERENCES "personal"."UNI_ORGANIZACIONAL"("UNI_ORG_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal"."UNI_ORGANIZACIONAL" ADD CONSTRAINT "FK_57389c843fe4bb2bcbb2c194ac2" FOREIGN KEY ("UNI_ORG_SUPERIOR_ID") REFERENCES "personal"."UNI_ORGANIZACIONAL"("UNI_ORG_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal"."FOTOGRAFIA" ADD CONSTRAINT "FK_6d432f4b03a985d8c1d62f13124" FOREIGN KEY ("PERS_ID") REFERENCES "personal"."PERSONA"("PERS_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "personal"."FOTOGRAFIA" DROP CONSTRAINT "FK_6d432f4b03a985d8c1d62f13124"`);
        await queryRunner.query(`ALTER TABLE "personal"."UNI_ORGANIZACIONAL" DROP CONSTRAINT "FK_57389c843fe4bb2bcbb2c194ac2"`);
        await queryRunner.query(`ALTER TABLE "personal"."PUESTO" DROP CONSTRAINT "FK_1cf2e9a0155543e21f6752e3b8b"`);
        await queryRunner.query(`ALTER TABLE "personal"."PUESTO_PERSONA" DROP CONSTRAINT "FK_bf6a131bac57fc997adc0dd514a"`);
        await queryRunner.query(`ALTER TABLE "personal"."PUESTO_PERSONA" DROP CONSTRAINT "FK_b918489c812772e156f97383be0"`);
        await queryRunner.query(`ALTER TABLE "personal"."PUESTO_PERSONA" DROP CONSTRAINT "FK_44111009eb8b30558c4e7b61610"`);
        await queryRunner.query(`ALTER TABLE "personal"."INFO_LABORAL" DROP CONSTRAINT "FK_a72764efdda4ee04814aee215b6"`);
        await queryRunner.query(`ALTER TABLE "personal"."INFO_LABORAL" DROP CONSTRAINT "FK_e4de6b93ddfcdc477096ba84d15"`);
        await queryRunner.query(`ALTER TABLE "personal"."INFO_LABORAL" DROP CONSTRAINT "FK_4eff75d32d86de14ab346208f67"`);
        await queryRunner.query(`ALTER TABLE "control-accesos"."CUENTA" DROP CONSTRAINT "FK_98117e3745f7518f76b23ea6613"`);
        await queryRunner.query(`ALTER TABLE "control-accesos"."USUARIO" DROP CONSTRAINT "FK_f4e92e02536b70e736a0e6f0a00"`);
        await queryRunner.query(`ALTER TABLE "control-accesos"."ROL" DROP CONSTRAINT "FK_a5f1d80b333b17b67938cb50437"`);
        await queryRunner.query(`ALTER TABLE "control-accesos"."ROL_CUENTA" DROP CONSTRAINT "FK_3a29ae5572589b33336f4daba87"`);
        await queryRunner.query(`ALTER TABLE "control-accesos"."ROL_CUENTA" DROP CONSTRAINT "FK_eaef5523322868c13f8391f594c"`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."actosadministrativos" DROP CONSTRAINT "FK_108deb1b6b2f15f68dfe22720a2"`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."actosadministrativos" DROP CONSTRAINT "FK_d0dd43ffeae86e51119bd06b0c1"`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."viaje" DROP CONSTRAINT "FK_2e9fa712def461e014af810173d"`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."pagocpt" DROP CONSTRAINT "FK_0a0dd54599b4c81234414040dec"`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."notificacion" DROP CONSTRAINT "FK_6d4c5eb7bc4c451fbe8842a3fa8"`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."reunion" DROP CONSTRAINT "FK_4973568d96d56889cd2f12ce114"`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."informe" DROP CONSTRAINT "FK_d5052c8c299e6cb52949aed2b43"`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."sujetoidentificado" DROP CONSTRAINT "FK_3a5ad1260d3102d8a8b7d53ceac"`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."providencia" DROP CONSTRAINT "FK_6dbbe7b7d52eb106fd39fdaf459"`);
        await queryRunner.query(`ALTER TABLE "consulta-previa"."resolucion" DROP CONSTRAINT "FK_61b40bd21c02dfe058232b54a34"`);
        await queryRunner.query(`DROP TABLE "personal"."FOTOGRAFIA"`);
        await queryRunner.query(`DROP TABLE "personal"."UNI_ORGANIZACIONAL"`);
        await queryRunner.query(`DROP TABLE "personal"."PUESTO"`);
        await queryRunner.query(`DROP TABLE "personal"."PUESTO_PERSONA"`);
        await queryRunner.query(`DROP TABLE "personal"."PERSONA"`);
        await queryRunner.query(`DROP TABLE "personal"."PARAMETRO"`);
        await queryRunner.query(`DROP TABLE "personal"."INFO_LABORAL"`);
        await queryRunner.query(`DROP TABLE "control-accesos"."CUENTA"`);
        await queryRunner.query(`DROP TABLE "control-accesos"."USUARIO"`);
        await queryRunner.query(`DROP TABLE "control-accesos"."ROL"`);
        await queryRunner.query(`DROP TABLE "control-accesos"."ROL_CUENTA"`);
        await queryRunner.query(`DROP TABLE "control-accesos"."GRUPO"`);
        await queryRunner.query(`DROP TABLE "consulta-previa"."actosadministrativos"`);
        await queryRunner.query(`DROP TABLE "consulta-previa"."viaje"`);
        await queryRunner.query(`DROP TABLE "consulta-previa"."pagocpt"`);
        await queryRunner.query(`DROP TABLE "consulta-previa"."tramite"`);
        await queryRunner.query(`DROP TABLE "consulta-previa"."notificacion"`);
        await queryRunner.query(`DROP TABLE "consulta-previa"."reunion"`);
        await queryRunner.query(`DROP TABLE "consulta-previa"."informe"`);
        await queryRunner.query(`DROP TABLE "consulta-previa"."sujetoidentificado"`);
        await queryRunner.query(`DROP TABLE "consulta-previa"."providencia"`);
        await queryRunner.query(`DROP TABLE "consulta-previa"."resolucion"`);
    }

}
